version: '3'

services:
  go_image_cdn:
    container_name: go_image_cdn
    build: .
    ports:
      - 3000:8080
    volumes:
      - .:/app
    command: go run ./ go
    stdin_open: true
    tty: true